name: opencadd
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - pip
  - numpy
  - jax
  - scipy
  - pandas
  - polars
  - matplotlib
  - jupyter
  - jupyterlab
  - mayavi
  - plotly
  - nglview
  - ipywidgets
  - ipyevents
  - ipympl
  - IPython
  - openbabel
  - autogrid
  - pdbfixer
  - openmm
  - pip:
      - -e caddpy/pkg
      - -e sciapi/pkg
      - -e scicoda/pkg
      - -e scids/pkg
      - -e scifile/pkg
      - -e scishow/pkg
      - -e t2fpharm/pkg
