name: t2fpharm
channels:
  - conda-forge
  - bioconda
dependencies:
  - python =3.12
  - numpy ==2.2.6
  - pandas ==2.3.1
  - pyarrow ==21.0.0
  - matplotlib ==3.10.3
  - tqdm ==4.67.1
  - pydantic ==2.11.7
  - scipy ==1.16.0
  - ipywidgets ==8.1.7
  - ipympl ==0.9.7
  - nglview ==3.1.4
  - numba ==0.61.2
  - beartype ==0.21.0
  - jaxtyping ==0.3.2
  - biopython ==1.85
  - openmm ==8.3.1
  - pdbfixer ==1.11
  - openbabel ==3.1.1
  - autogrid ==4.2.6
  - jupyter_core ==5.8.1
  - jupyterlab ==4.4.5
  - IPython ==9.4.0
  - pip
  - pip:
    - arrayer ==0.0.6
    - bbo ==0.0.2
    - commonnn-clustering ==0.0.4
    - fileex ==0.2.4
    - jax ==0.7.0
    - pkgdata ==0.1.2
    - plip ==2.4.0
    - pylinks ==0.1.0
    - pyserials ==0.1.1
    - pyshellman ==0.1.0
    - ray ==2.48.0

    - -e caddpy/pkg
    - -e sciapi/pkg
    - -e scicoda/pkg
    - -e scids/pkg
    - -e scifile/pkg
    - -e scishow/pkg
    - -e t2fpharm/pkg
    - -e t2fpharm/study/pkg

