name: opencadd
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - jax
  - scipy
  - pandas
  - polars
  - matplotlib
  - jupyter
  - jupyterlab
  - mayavi
  - plotly
  - nglview
  - ipywidgets
  - ipyevents
  - ipympl
  - IPython
  - openbabel
  - pip:
      - -e sciapi/pkg
      - -e scids/pkg
      - -e t2fpharm/pkg
