name: t2fpharm
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - jax
  - pandas
  - scipy
  - nglview
  - openbabel
  - polars
  - matplotlib
  - ipywidgets
  - IPython
  - requests
  - jupyterlab
  - mayavi
  - plotly
  - ipyevents
  - ipympl
  - pip
  - pip:
      - -e .
