[build-system]
requires = ["setuptools>=61.0", "versioningit"]
build-backend = "setuptools.build_meta"

[project]
name = "T2FPharm"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "pydantic",

    "scids",
    "scifile",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true
