{% set name = "structuralalignment" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../

  # sha256: d58439c548433adcda98e695be53e526ba940a4b9c44fb9a05d92cd495cdd47f
  # sha256 needs to be edited

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - structuralalignment = structuralalignment.cli:main

requirements:
  host:
    - python
    - pip

  run:
    - python
    - atomium
    - biotite
    - MDAnalysis
    - structuralalignment
    - muscle

test:
  imports:
    - structuralalignment
  commands:
    - structuralalignment -h

about:
  home: https://github.com/volkamerlab/structuralalignment
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python library for molecular structural alignment and superposition'

  description: |
    structuralalignment is a Python library for molecular alignmnet and
    superposition with different methods like theseus, mmligner and
    Chimera-Matchmaker.
  doc_url: https://structural-alignment.readthedocs.io/en/latest/
  dev_url: https://github.com/volkamerlab/structuralalignment

extra:
  recipe-maintainers:
    - pipaj97
    - jaimergp