"""
Detect binding pockets using DoGSiteScorer web API.

at DoGSiteScorer functionality of ProteinsPlus server.

References
----------
1.  Volkamer, A.; Griewel, A.; Grombacher, T.; Rarey, M.,
    Analyzing the topology of active sites: on the prediction of pockets and subpockets.
    J. Chem. Inf. Model. 2010, 50 (11), 2041-52. DOI: https://doi.org/10.1021/ci100241y.
2.  Volkamer, A.; Kuhn, D.; Grombacher, T.; Rippmann, F.; Rarey, M.,
    Combining global and local measures for structure-based druggability predictions.
    J. Chem. Inf. Model. 2012, 52 (2), 360-72. DOI: https://doi.org/10.1021/ci200454v.
"""

import gzip
import io
from collections.abc import Sequence
import re

import numpy as np
import pandas as pd

import opencadd as oc
import opencadd._common_webapi
import opencadd._regex

# from opencadd.io.io import filelike_to_filepath
from opencadd._decorator import RetryConfig
from opencadd._http_request import HTTPRequestRetryConfig, response_http_request


class DoGSiteScorerDetector:
    """DoGSiteScorer binding site detector.

    Parameters
    ----------
    ensemble
    pocket_data
    pocket_atoms
    pocket_volumes
    data_description : str
        Description of data descriptors used by DoGSiteScorer.
    """

    def __init__(
        self,
        ensemble,
        pockets,
        pocket_data,
        pocket_atoms,
    ):
        self._ensemble = ensemble
        self._pockets = pockets
        self._pocket_data = pocket_data
        self._pocket_atoms = pocket_atoms
        return

    @property
    def ensemble(self):
        return self._ensemble

    @property
    def pockets(self):
        return self._pockets

    @property
    def pocket_data(self):
        """

        Returns
        -------
        pandas.DataFrame
            Columns:


        """
        return self._pocket_data

    @property
    def pocket_atoms(self):
        return self._pocket_atoms

    @property
    def best_coverage(self) -> str:
        """
        Name of the pocket with the highest total coverage for the selected ligand.

        Total coverage is calculated as the product of ligand coverage and pocket coverage.

        Returns
        -------
        str
            Name of the pocket.
        """
        return (self.pocket_data.lig_cov * self.pocket_data.poc_cov).idxmax()


def _from_ensemble(
    ensemble: oc.chem.ensemble.ChemicalSystem,
    model: int | None = 0,
    chain_id: str | None = None,
    ligand_id_chain_num: tuple[str, str, int] | None = None,
    include_subpockets: bool = True,
    calculate_druggability: bool = True,
    retry_config: HTTPRequestRetryConfig | None = HTTPRequestRetryConfig(),
) -> DoGSiteScorerDetector:
    dummy_pdb_id = oc._common_webapi.proteinsplus_upload_pdb(
        pdb_content=ensemble.to_pdb(model=model)
    )
    pocket_data_df, atoms_df, pocket_volumes, description = _run(
        pdb_id=dummy_pdb_id,
        chain_id=chain_id,
        ligand_id_chain_num=ligand_id_chain_num,
        include_subpockets=include_subpockets,
        calculate_druggability=calculate_druggability,
        retry_config=retry_config,
    )
    pockets = {
        pocket_name: oc.pocket.BindingPocket(
            ensemble=ensemble,
            volume=volume,
            atoms=atoms_df.loc[pocket_name, "atom_serial"].to_numpy(),
        )
        for volume, pocket_name in zip(pocket_volumes, pocket_data_df.index, strict=False)
    }
    return DoGSiteScorerDetector(
        ensemble=ensemble, pockets=pockets, pocket_data=pocket_data_df, pocket_atoms=atoms_df
    )



def _parse_results(pockets_table: str, ccp4_files: Sequence[bytes], pdb_files: Sequence[bytes]):
    """Parse the PDB files generated by DoGSiteScorer for each detected pocket.

    Parameters
    ----------
    contents : sequence of bytes
        A sequence of PDB file contents, each as bytes.
    pocket_names : sequence of str
        Name of each pocket, corresponding to `contents`.

    Returns
    -------
    atoms_df, pocket_centers, pocket_radii : pandas.DataFrame, numpy.ndarray, numpy.ndarray
        * atoms_df: Table of atom serials for each pocket.
        * pocket_centers: Coordinates of the geometric center of each pocket.
        * pocket_radii: Maximum radius of each pocket.
    """
    # Create a pandas DataFrame from the pockets' data.
    pocket_data_df = pd.read_csv(io.StringIO(pockets_table), sep="\t").set_index("name")
    # Parse the PDB files; they contain ATOM records from the input PDB file,
    #  corresponding to a specific pocket's residues.
    #  They also contain the geometric center and the max. radius of the pockets.
    pocket_names_repeated, atom_serials, pocket_centers, pocket_radii = [], [], [], []




    for name, content in zip(pocket_data_df.index, pdb_files, strict=False):
        lines = content.decode().splitlines()
        info_line = lines[5]
        center_and_radius = [
            float(elem) for elem in info_line.split() if any_num_regex.match(elem)
        ]
        pocket_centers.append(center_and_radius[:3])
        pocket_radii.append(center_and_radius[3])
        serials = [int(line[6:11]) for line in lines[6:]]
        atom_serials.extend(serials)
        pocket_names_repeated.extend([name] * len(serials))
    # Add centers and radii to the dataframe
    pocket_data_df[["center_x", "center_y", "center_z"]] = np.array(pocket_centers)
    pocket_data_df["max_radius"] = pocket_radii
    # Create another dataframe for atom serial numbers of each pocket
    atoms_df = pd.DataFrame(data={"atom_serial": atom_serials}, index=pocket_names_repeated)
    atoms_df.index.name = "name"
    # Parse CCP4 map files to volumes
    pocket_volumes = [
        oc.io.ccp4.mrc.from_file_content(gzip.decompress(ccp4)) for ccp4 in ccp4_files
    ]
    return pocket_data_df, atoms_df, pocket_volumes
