#!/bin/bash
name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  schedule:
    # Nightly Tests
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.7, 3.8]
    env:
      CI_OS: ${{ matrix.os }}
      PACKAGE: "structuralalignment"

    steps:
      - uses: actions/checkout@v2
      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a
      - name: Fix conda in MacOS
        shell: bash
        if: startsWith(matrix.os, 'macOS')
        run: |
          sudo chown -R $(id -u):$(id -g) ${CONDA}
      - name: Create environment for package
        shell: bash
        run: |
          . devtools/scripts/initialize_conda.sh
          conda activate
          conda info --all
          python devtools/scripts/create_conda_env.py -n=test -p=${{ matrix.python-version }} devtools/conda-envs/test_env.yaml
      - name: Install package
        shell: bash
        run: |
          . devtools/scripts/initialize_conda.sh
          conda activate test
          python -m pip install . --no-deps
          conda list
      - name: Run tests
        shell: bash
        run: |
          . devtools/scripts/initialize_conda.sh
          conda activate test
          pytest -v --cov=${PACKAGE} --cov-report=xml --color=yes ${PACKAGE}/tests/
      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          yml: ./.codecov.yml
  #############
  lint-format:
    runs-on: ubuntu-latest
    env:
      CI_OS: ubuntu-latest
      PACKAGE: "structuralalignment"
      PYVER: "3.7"

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install linter and formatter
        shell: bash
        run: |
          . devtools/scripts/initialize_conda.sh
          conda activate
          python devtools/scripts/create_conda_env.py -n=test -p=$PYVER devtools/conda-envs/test_env.yaml
          conda activate test
          conda install -y pylint black
      - name: Run pylint
        shell: bash
        run: |
          . devtools/scripts/initialize_conda.sh
          conda activate test
          pylint $PACKAGE/
      - name: Run black check
        shell: bash
        if: always()
        run: |
          . devtools/scripts/initialize_conda.sh
          conda activate test
          black --check -l 99 $PACKAGE/ --exclude $PACKAGE/_version.py
  #############
  docs:
    runs-on: ubuntu-latest
    env:
      CI_OS: ubuntu-latest
      PACKAGE: "structuralalignment"
      PYVER: "3.7"

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Create environment
        shell: bash
        run: |
          . devtools/scripts/initialize_conda.sh
          conda activate
          python devtools/scripts/create_conda_env.py -n=test -p=$PYVER devtools/conda-envs/test_env.yaml
      - name: Run sphinx
        shell: bash
        run: |
          . devtools/scripts/initialize_conda.sh
          cd docs
          make clean
          SPHINXOPTS="-W -T --keep-going" make html
