name: Docs

on:
  push:
    branches:
      - "master"
      - "dev"
  pull_request:
    branches:
      - "master"
      - "dev"
  schedule:
    # Run a cron job once weekly on Monday
    - cron: "0 3 * * 1"

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      CI_OS: ubuntu-latest
      PACKAGE: "opencadd"
      PYVER: "3.9"

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.9"
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: test
          environment-file: devtools/conda-envs/test_env.yaml
          channels: conda-forge,defaults,bioconda

      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          conda list

      - name: Run sphinx
        shell: bash -l {0}
        run: |
          cd docs
          make clean
          SPHINXOPTS="-W -T --keep-going" make html
