name: Lint

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"
  schedule:
    # Weekly tests run on main by default:
    #  Scheduled workflows run on the latest commit on the default or base branch.
    #  see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
    - cron: "0 3 * * 1"  # Run a weekly cron job at 03:00 on Mondays

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      CI_OS: ubuntu-latest
      PACKAGE: "opencadd"
      PYVER: "3.10"
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: devtools/conda-envs/test_env.yaml
          environment-name: test
          channels: conda-forge,defaults
          extra-specs: |
            python=3.10
      - name: Install linter and formatter
        shell: bash -l {0}
        run: |
          conda install -y pylint black
      - name: Run pylint
        shell: bash -l {0}
        run: |
          pylint $PACKAGE/
      - name: Run black check
        shell: bash -l {0}
        if: always()
        run: |
          black --check -l 119 $PACKAGE/
