{% set name = "mmligner" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://lcb.infotech.monash.edu.au/{{ name }}/files/{{ name }}_{{ version }}.tar.gz
  sha256: 0208e8fd1eb0492a13d1bfcba53a7a97f96023f18e3982e334962f0ce1c69f07

build:
  number: 0
  script: #?

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

test:
  # TODO: Find simple tests because mmligner -h raises input error
  imports:


about:
  home: http://lcb.infotech.monash.edu.au/{{ name }}/
  license: GPL-3.0
  license_file: LICENSE.txt
  summary: 'tool for statistical inference of protein stuctual alignment'

  description: |
    MMLigner is tool for statistical inference of protein stuctual alignment
    using information and compression written entirely in C++.

extra:
  recipe-maintainers:
    - Koesed96
